AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 45

Metrics/ParameterLists:
  Max: 7
