[mothership]
metrics_port = 9090

[mothership.bind]
http = "0.0.0.0:8080"

[[bays.http]]
name = "web"
command = "bundle"
args = ["exec", "shuttlebay", "config.ru"]
workers = 0
threads = 5
routes = [{ bind = "http", pattern = "/.*" }]

[[fleet.workers]]
name = "scheduler"
command = "bundle"
args = ["exec", "ruby", "bin/scheduler"]
critical = true
tags = ["scheduler"]
